server:
  port: 7003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true #eureka url以Ip形式存在
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7004/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.1
