server:
  port: 7003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.1
