server:
  port: 7003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-master
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true #eureka url以Ip形式存在
  client:
    registerWithEureka: true #将自己做为服务注册到其他注册中心
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-slave:7004/eureka/
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.1
