server:
  port: 8088
spring:
    application:
       name: spc-test-server
    cloud:
       config:
         server:
            git:
               uri: https://github.com/zhangmenyucom/config-center
               
logging:
  level: debug
