server:
  port: 8008
spring:
  datasource:
    url: jdbc:mysql://rds709d4qk8m0ibqr706.mysql.rds.aliyuncs.com:3306/o2o?characterEncoding=utf8
    password: 1q2w3e4r5_A
    username: o2odev
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 1000
      max-active: 200
      max-idle: 10
      test-on-borrow: true
  redis:
    host: e54912538ba64881.m.cnhza.kvstore.aliyuncs.com
    password: e54912538ba64881:1q2w3e4r5A
    port: 6379
    timeout: 1000
    database: e54912538ba64881
    pool:
      max-active: 200
      max-idle: 10
      max-wait: 1000
  activemq:
    broker-url: tcp://10.12.64.189:61611
    user:
    password:
    pool:
      enabled: true
      configuration:
        maximum-active-session-per-connection: 10
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.dev.zd.internal.weimob.com/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 31
logging:
  level:
    root: INFO
    com.weimob: DEBUG
zuul:
  internal:
    url: http://zuul.dev.zd.internal.weimob.com/
counsumer:
  orderPayedDestination:
    count: 1-2
  publishMemberCardDestination:
    count: 1-2
