spring:
  application:
    name: zuul-api-gate
  cloud:
    loadbalancer:
     retry:
       enabled: true
    config:
      username: user
      password: 7cc3d4c3-9fda-48be-bb7f-6bd304c2ec57

server:
  port: 7002
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/
    registry-fetch-interval-seconds: 20

  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 4
    preferIpAddress: true
  server:
    renewal-percent-threshold: 0.1

zuul:
  ignoredServices: '*'
  routes:
    account:
      path: /test-client/**
      serviceId: spc-test-client
      sensitiveHeaders:
      stripPrefix: true
  add-host-header: true
  retryable: true
