server:
  port: 7003
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangmenyucom/config-center
          searchPaths: '{application}'
          clone-on-start: true
          default-label: master
          username: zhangmenyucom
          password: VBN123vbn

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    preferIpAddress: true