server:
  port: 9001
spring:
  application:
    name: feign-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/,http://localhost:7003/eureka/ #获取服务列表地址
      registry-fetch-interval-seconds: 20 #定时向eureka Server请求刷新服务列表时间，默认30
  instance:
    preferIpAddress: true #注册时以ip注册
    lease-renewal-interval-in-seconds: 20 #定时向eureka-server续约时间，表示自已还存活着
    lease-expiration-duration-in-seconds: 60 #超过这个时间如果没有续约则被eureka-server剔除掉
logging:
  level:
   com:
    taylor:
      service:
        HelloService: debug
   root: info

feign:
  compression:
    request:
      mime-types: text/xml,application/xml/,application/json #压缩类型
      min-request-size: 2048 #超过这个值会进行压缩



