server:
  port: 8082
spring:
  application:
    name: eureka-client
eureka:
  instance:
    hostname: eureka-client-dev
    lease-renewal-interval-in-seconds: 30 #eureka客户端向服务端发送心跳的间隔
    lease-expiration-duration-in-seconds: 90 #超过此时间没有续约的服务将被剔除掉
    prefer-ip-address: true #是否优先使用ip地址作为主机名的标识
  client:
    registerWithEureka: true #是否自己也做为服务注册到其他注册中心，集群下设为true
    fetchRegistry: true #是否缓存服务列表
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #eureka-sever地址列表，以分号隔开
logging:
  level: INFO
example:
    service:
      enabled: true
      config: abc-des-dde,SSS-DRS-RE,SDR-SDFR-XXX