name: zhangsan12321
content: "${name}" I am a littler small drag and happy all the time with you please don't leave me alone haah
server:
  port: 8080
spring:
  application:
    name: spc-test-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 31
logging:
  level: INFO