name: zhangsan12321
content: I am a littler small drag**************11111
server:
  port: 8081
spring:
 application:
    name: spc-service-client
  cloud:
    loadbalancer:
     retry:
       enabled: true
  rabbitmq:
    host: 192.168.186.128
    port: 5672
    username: spring-cloud
    password: guest
management:
  security:
    enabled: false #可以在浏览器中查看节点的健康状况

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/,http://localhost:7003/eureka/ #获取服务列表地址
      registry-fetch-interval-seconds: 20 #定时向eureka Server请求刷新服务列表时间，默认30
    healthCheck:
      enabled: true
  instance:
    preferIpAddress: true #注册时以ip注册
    lease-renewal-interval-in-seconds: 20 #定时向eureka-server续约时间，表示自已还存活着
    lease-expiration-duration-in-seconds: 60 #超过这个时间如果没有续约则被eureka-server剔除掉

ribbon:
  ReadTimeout: 8000 #读取时间
  ConnectTimeout: 8000 #路由时间
  OkToRetryOnAllOperations: true  #对所有操作请求都进行重试
  MaxAutoRetries: 1 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 #对下个实例的重试次数

logging:
  level: INFO